"""First migration

Revision ID: 06a6a6e0635f
Revises: 
Create Date: 2020-09-29 02:27:54.131365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a6a6e0635f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('abbreviation', sa.String(length=50), nullable=True),
    sa.Column('colour', sa.String(length=10), nullable=True),
    sa.Column('text_color', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=50), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('list_as', sa.String(length=200), nullable=True),
    sa.Column('represents', sa.String(length=200), nullable=True),
    sa.Column('is_landlord', sa.Boolean(), nullable=True),
    sa.Column('expl_txt', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    op.drop_table('parties')
    # ### end Alembic commands ###
